//Action types

export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST";
export const POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS";
export const POST_IMAGE_FAILURE = "POST_IMAGE_FAILURE";
export const POST_IMAGE_RESET = "POST_IMAGE_RESET";

export const UPDATE_IMAGE_REQUEST = "UPDATE_IMAGE_REQUEST";
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_FAILURE = "UPDATE_IMAGE_FAILURE";
export const UPDATE_IMAGE_RESET = "POST_IMAGE_RESET";

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAILURE = "DELETE_IMAGE_FAILURE";

export const GET_IMAGES_REQUEST = "GET_IMAGES_REQUEST";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAILURE = "GET_IMAGES_FAILURE";

export const GET_IMAGE_DETAILS_REQUEST = "GET_IMAGE_DETAILS_REQUEST";
export const GET_IMAGE_DETAILS_SUCCESS = "GET_IMAGE_DETAILS_SUCCESS";
export const GET_IMAGE_DETAILS_FAILURE = "GET_IMAGE_DETAILS_FAILURE";
